Repository eoscostarica/lifebank, pull requests merged in 2020-10, with the labels that each got.

#254 fix: hasura conflicts
  hasura/migrations/1590526643953_create_table_public_user/up.sql
  hasura/migrations/1601327631743_create_table_public_verificate_email/up.sql
  hasura/migrations/1601330035486_delete_fk_public_verificate_email_verificate_email_email_fkey/down.sql
  hasura/migrations/1601330035486_delete_fk_public_verificate_email_verificate_email_email_fkey/up.sql
  hasura/migrations/1601330204205_delete_fk_public_verificate_email_verificate_email_email_fkey1/down.sql
  hasura/migrations/1601330204205_delete_fk_public_verificate_email_verificate_email_email_fkey1/up.sql
Labels: bug

#248 Donor on boarding flow
  hapi/src/api/account.api.js
  hapi/src/routes/create-account/create-account.validation.js
  hasura/metadata/actions.graphql
  webapp/package.json
  webapp/src/components/LoginModal/Login.js
  webapp/src/components/LoginModal/LoginWithFacebook.js
  webapp/src/components/LoginModal/LoginWithGoogle.js
  webapp/src/config/index.js
  webapp/src/config/oAuth.config.js
  webapp/src/gql/account.gql.js
  webapp/src/routes/Signup/Signup.js
  webapp/src/routes/Signup/SignupDonor.js
  webapp/src/routes/Signup/ValidateEmail.js
  webapp/src/routes/Signup/socialSingup/SignupWithFacebook.js
  webapp/src/routes/Signup/socialSingup/SignupWithGoogle.js
  webapp/yarn.lock
  yarn.lock
Labels: frontend

#261 feat: email verification
  hapi/src/api/account.api.js
  hapi/src/api/pre-register.api.js
  hapi/src/api/user.api.js
  hapi/src/routes/index.js
  hapi/src/routes/verify-email/verify-email.handler.js
  hapi/src/routes/verify-email/verify-email.route.js
  hapi/src/routes/verify-email/verify-email.validation.js
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  hasura/migrations/1602017248967_alter_table_public_preregister_lifebank_add_column_email_verified/down.sql
  hasura/migrations/1602017248967_alter_table_public_preregister_lifebank_add_column_email_verified/up.sql
  webapp/src/gql/account.gql.js
  webapp/src/routes/EmailVerification/EmailVerification.js
  webapp/src/routes/EmailVerification/index.js
  webapp/src/routes/index.js
Labels: backend, frontend

#264 fix: add delete offer confirmation
  webapp/src/routes/OffersManagement/OffersManagement.js
Labels: frontend

#266 Feat/splash intro component
  webapp/package.json
  webapp/src/App.js
  webapp/src/assets/fourth.svg
  webapp/src/assets/lifebank.svg
  webapp/src/assets/second.svg
  webapp/src/assets/third.svg
  webapp/src/components/SplashIntro/SplashIntro.js
  webapp/src/components/SplashIntro/index.js
  webapp/src/index.css
  webapp/src/index.js
  webapp/yarn.lock
  yarn.lock
Labels: frontend

#269 feat: splash intro desktop
  webapp/src/components/SplashIntro/SplashIntro.js
Labels: frontend

#273 fix: fix edit offer bug
  webapp/src/gql/offer.gql.js
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OfferDetails.js
Labels: bug, frontend

#274 Feat/splash intro desktop
  webapp/package.json
  webapp/src/App.js
  webapp/src/assets/fourth.svg
  webapp/src/assets/second.svg
  webapp/src/assets/third.svg
  webapp/src/components/SplashIntro/SplashIntro.js
  webapp/src/index.css
  webapp/yarn.lock
  yarn.lock
Labels: bug

#275 Front end redesign
  hasura/metadata/tables.yaml
  webapp/src/components/LanguageSelector/LanguageSelector.js
  webapp/src/components/LifebankIcon/LifebankIcon.js
  webapp/src/components/LoginModal/Login.js
  webapp/src/components/MapModal/MapModal.js
  webapp/src/components/Notification/Notification.js
  webapp/src/components/Notification/index.js
  webapp/src/containers/Main.js
  webapp/src/containers/TopBar.js
  webapp/src/gql/location.gql.js
  webapp/src/routes/Home/Home.js
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/Home/ShowOffers.js
  webapp/src/routes/Home/ShowSponsors.js
  webapp/src/routes/Home/index.js
  webapp/src/routes/Offers/Offers.js
  webapp/src/routes/Offers/index.js
  webapp/src/routes/index.js
Labels: frontend

#276 fix: login with facebook or google auth
  webapp/src/components/LoginModal/Login.js
Labels: bug

#277 Feat/splash intro desktop
  webapp/src/components/SplashIntro/SplashIntro.js
  webapp/src/index.css
Labels: bug

#285 update navbar design
  webapp/src/components/LanguageSelector/LanguageSelector.js
  webapp/src/components/Notification/Notification.js
  webapp/src/containers/Main.js
  webapp/src/containers/TopBar.js
Labels: frontend

#286 Slide cards
  webapp/src/routes/Home/Home.js
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/Home/ShowOffers.js
  webapp/src/routes/Home/ShowSponsors.js
Labels: frontend

#287 fix: fit filter dialog on small screens
  webapp/src/components/MapShowLocations/index.js
Labels: frontend

#289 front-page UX problems
  webapp/src/components/FilterHome/FilterHome.js
  webapp/src/components/FilterHome/index.js
  webapp/src/components/MapModal/MapModal.js
  webapp/src/routes/Home/Home.js
  webapp/src/routes/Home/HomeDesktop.js
  webapp/src/routes/Home/HomeMobile.js
Labels: UX / UI, frontend

#268 fix: fix complete sponsor info functionality
  hapi/src/api/account.api.js
  webapp/src/components/Logo/Logo.js
  webapp/src/routes/EditProfile/EditProfile.js
  webapp/src/routes/EditProfile/EditProfileSponsor.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
  webapp/src/routes/Signup/SignupSponsor/SimpleRegisterForm.js
Labels: bug

#297 Lifebank node initialization script
  .gitignore
  contracts/scripts/lifebank.sh
Labels: smart contracts

#296 Donations dashboard
  webapp/debug.log
  webapp/src/components/DonationsDashboard/DonationsDashboard.js
  webapp/src/components/DonationsDashboard/index.js
  webapp/src/routes/Home/HomeDesktop.js
  webapp/src/routes/Home/HomeMobile.js
Labels: UX / UI, frontend

#314 Feat/i18n
  webapp/src/components/Carousel/Carousel.js
  webapp/src/components/ClaimReward/ClaimReward.js
  webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
  webapp/src/components/DonationsDashboard/DonationsDashboard.js
  webapp/src/components/FilterHome/FilterHome.js
  webapp/src/components/LanguageSelector/LanguageSelector.js
  webapp/src/components/LoginModal/Login.js
  webapp/src/components/LoginModal/LoginWithFacebook.js
  webapp/src/components/LoginModal/LoginWithGoogle.js
  webapp/src/components/MapModal/MapModal.js
  webapp/src/components/MapPopup/index.js
  webapp/src/components/MapShowLocations/index.js
  webapp/src/components/MapStatic/index.js
  webapp/src/components/Notification/Notification.js
  webapp/src/components/Schedule/Schedule.js
  webapp/src/components/SplashIntro/SplashIntro.js
  webapp/src/components/TokenTransfer/TokenTransfer.js
  webapp/src/containers/SideBar.js
  webapp/src/containers/TopBar.js
  webapp/src/i18n.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/About/About.js
  webapp/src/routes/Dashboard/DashboardProfile.js
  webapp/src/routes/Donation/DonationPage.js
  webapp/src/routes/EditProfile/EditProfile.js
  webapp/src/routes/EditProfile/EditProfileBank.js
  webapp/src/routes/EditProfile/EditProfileDonor.js
  webapp/src/routes/EditProfile/EditProfileSponsor.js
  webapp/src/routes/EmailVerification/EmailVerification.js
  webapp/src/routes/Help/Help.js
  webapp/src/routes/Home/HomeDesktop.js
  webapp/src/routes/Home/HomeMobile.js
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/Home/ShowOffers.js
  webapp/src/routes/Home/ShowSponsors.js
  webapp/src/routes/InfoPage/InfoPage.js
  webapp/src/routes/LandingPage/LandingPage.js
  webapp/src/routes/NotFound/NotFound.js
  webapp/src/routes/OfferPage/OfferPage.js
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OfferDetails.js
  webapp/src/routes/OffersManagement/OffersManagement.js
  webapp/src/routes/Profile/ProfilePage.js
  webapp/src/routes/Profile/ProfilePageDonor.js
  webapp/src/routes/Profile/ProfilePageGuest.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
  webapp/src/routes/Signup/Signup.js
  webapp/src/routes/Signup/SignupAccount.js
  webapp/src/routes/Signup/SignupConsent.js
  webapp/src/routes/Signup/SignupDonor.js
  webapp/src/routes/Signup/SignupLifeBank.js
  webapp/src/routes/Signup/SignupRoleSelector.js
  webapp/src/routes/Signup/SignupSponsor/SimpleRegisterForm.js
  webapp/src/routes/Signup/SignupUsername.js
  webapp/src/routes/Signup/ValidateEmail.js
  webapp/src/routes/Signup/socialSingup/SignupWithFacebook.js
  webapp/src/routes/Signup/socialSingup/SignupWithGoogle.js
Labels: i18n

#324 feat: offer view
  webapp/src/components/DonationsDashboard/DonationsDashboard.js
  webapp/src/components/MapModalOneLocation/LocatorDonators.js
  webapp/src/components/MapModalOneLocation/LocatorSponsor.js
  webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
  webapp/src/components/MapModalOneLocation/index.js
  webapp/src/components/OfferView/OfferView.js
  webapp/src/components/OfferView/index.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/Home/ShowOffers.js
Labels: frontend
