Repository eoscostarica/lifebank, pull requests merged in 2020-12, with the labels that each got.

#403 fix: add some performance tweaks
  nginx.conf
  webapp/nginx.conf
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.js
  webapp/src/components/Nearby/Nerby.js
  webapp/src/components/OfferView/OfferView.js
  webapp/src/config/index.js
  webapp/src/config/ual-config.js
  webapp/src/index.js
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/Home/ShowOffers.js
  webapp/src/routes/Home/ShowSponsors.js
  webapp/src/routes/InfoPage/InfoPage.js
  webapp/yarn.lock
Labels: testing

#410 fix: delete cache assets config
  nginx.conf
  webapp/nginx.conf
  webapp/public/index.html
Labels: bug

#415 fix splash intro loading
  webapp/src/App.js
  webapp/src/components/SplashIntro/SplashIntro.js
Labels: bug

#417 feat: add sitemap
  webapp/package.json
  webapp/src/sitemap.xml
  webapp/yarn.lock
Labels: SEO, enhancement

#418 Dashboard fixes
  webapp/src/components/DonationsDashboard/DonationsDashboard.js
  webapp/src/components/OfferView/OfferView.js
  webapp/src/routes/Home/HomeDesktop.js
  webapp/src/routes/Home/HomeMobile.js
Labels: frontend

#428 wip: fix structured data
  webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js
  webapp/src/components/MedicalClinicStructuredData/MedicalClinicStructuredData.js
  webapp/src/routes/Home/Home.js
Labels: bug

#432 fix: missing parse in el.photos
  webapp/src/routes/Home/Home.js
Labels: bug

#437 fix: add photos validation in account api
  hapi/src/api/account.api.js
  webapp/Dockerfile
  webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js
  webapp/src/components/MedicalClinicStructuredData/MedicalClinicStructuredData.js
Labels: bug

#444 Profile design
  webapp/src/routes/Profile/ProfilePage.js
  webapp/src/routes/Profile/ProfilePageDonor.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
Labels: frontend

#458 Change empty state in nearby locations
  webapp/src/components/Nearby/Nerby.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/InfoPage/InfoPageDesktop.js
Labels: frontend

#452 Fix/add url field to structured data
  webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js
  webapp/src/components/MapPopup/index.js
  webapp/src/components/MapShowOneLocation/index.js
  webapp/src/components/MedicalClinicStructuredData/MedicalClinicStructuredData.js
  webapp/src/index.js
  webapp/src/routes/Home/Home.js
Labels: bug

#459 fix max width
  webapp/src/containers/Main.js
  webapp/src/routes/Home/HomeDesktop.js
Labels: frontend

#457 Redesign edit profile section
  webapp/src/components/Carousel/Carousel.js
  webapp/src/components/Logo/Logo.js
  webapp/src/components/LogoUrlInput/LogoUrlInput.js
  webapp/src/components/Schedule/Schedule.js
  webapp/src/components/SocialMediaTextField/SocialMediaTextField.js
  webapp/src/components/Telephones/Telephones.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/EditProfile/EditProfile.js
  webapp/src/routes/EditProfile/EditProfileBank.js
  webapp/src/routes/EditProfile/EditProfileDonor.js
  webapp/src/routes/EditProfile/EditProfileSponsor.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
Labels: frontend

#462 update offer management design
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OfferDetails.js
  webapp/src/routes/OffersManagement/OffersManagement.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
Labels: frontend
