Repository eoscostarica/lifebank, pull requests merged in 2020-09, with the labels that each got.

#226 fix hrefs values
  README.md
  contracts/consent2life/README.md
  contracts/lifebankcode/README.md
  contracts/lifebankcoin/README.md
  docker-compose.yaml
  webapp/Dockerfile
  webapp/src/components/MapPopup/index.js
  webapp/src/components/RicardianContract/RicardianContract.js
  webapp/src/components/TokenTransfer/TokenTransfer.js
  webapp/src/config/eos.config.js
  webapp/src/config/index.js
  webapp/src/routes/Dashboard/DashboardProfile.js
  webapp/src/routes/Profile/ProfilePage.js
  webapp/src/routes/Profile/ProfilePageDonor.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
  webapp/src/routes/Signup/SignupAccount.js
Labels: Medium Priority, frontend

#231 Feature: Sponsor Offer Management
  hapi/src/api/account.api.js
  hapi/src/api/user.api.js
  hasura/metadata/tables.yaml
  hasura/migrations/1599163895451_drop_table_public_offer/up.sql
  hasura/migrations/1599164128791_create_table_public_offer/down.sql
  hasura/migrations/1599164128791_create_table_public_offer/up.sql
  hasura/migrations/1599172301860_alter_table_public_offer_alter_column_quantity/down.sql
  hasura/migrations/1599172301860_alter_table_public_offer_alter_column_quantity/up.sql
  hasura/migrations/1599172351869_alter_table_public_offer_alter_column_images/down.sql
  hasura/migrations/1599172351869_alter_table_public_offer_alter_column_images/up.sql
  hasura/migrations/1599686092964_alter_table_public_offer_add_column_offer_name/down.sql
  hasura/migrations/1599686092964_alter_table_public_offer_add_column_offer_name/up.sql
  hasura/migrations/1599689752625_alter_table_public_offer_add_column_active/down.sql
  hasura/migrations/1599689752625_alter_table_public_offer_add_column_active/up.sql
  webapp/package.json
  webapp/src/components/Carousel/Carousel.js
  webapp/src/components/Carousel/index.js
  webapp/src/containers/SideBar.js
  webapp/src/gql/account.gql.js
  webapp/src/gql/index.js
  webapp/src/gql/offer.gql.js
  webapp/src/routes/Dashboard/DashboardSidebar.js
  webapp/src/routes/OffersManagement/AddOffer.js
  webapp/src/routes/OffersManagement/OfferDetails.js
  webapp/src/routes/OffersManagement/OffersManagement.js
  webapp/src/routes/OffersManagement/index.js
  webapp/src/routes/Signup/Signup.js
  webapp/src/routes/Signup/SignupSponsor/SignupSponsor.js
  webapp/src/routes/Signup/SignupSponsor/index.js
  webapp/src/routes/index.js
  webapp/yarn.lock
Labels: Medium Priority, enhancement, frontend

#233 Edit Functionality
  webapp/src/gql/offer.gql.js
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OffersManagement.js
Labels: Medium Priority, frontend

#235 fix: remove unexpected drop migration
  hasura/migrations/1599163895451_drop_table_public_offer/up.sql
Labels: bug

#237 fix: allow open dialog to add new offer. Add proper validation
  webapp/src/routes/OffersManagement/OffersManagement.js
Labels: bug

#240 fix/hide sidebar item acorrding to role
  webapp/src/components/Carousel/Carousel.js
  webapp/src/containers/SideBar.js
Labels: bug

#241 Feat/additional offer fields
  hasura/metadata/tables.yaml
  hasura/migrations/1600362595610_alter_table_public_offer_add_column_const_in_tokens/down.sql
  hasura/migrations/1600362595610_alter_table_public_offer_add_column_const_in_tokens/up.sql
  hasura/migrations/1600362624704_alter_table_public_offer_alter_column_const_in_tokens/down.sql
  hasura/migrations/1600362624704_alter_table_public_offer_alter_column_const_in_tokens/up.sql
  hasura/migrations/1600362903320_alter_table_public_offer_alter_column_const_in_tokens/down.sql
  hasura/migrations/1600362903320_alter_table_public_offer_alter_column_const_in_tokens/up.sql
  webapp/src/gql/offer.gql.js
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OfferDetails.js
Labels: enhancement, frontend

#242 feat: offer pages
  hasura/metadata/tables.yaml
  webapp/debug.log
  webapp/src/containers/SideBar.js
  webapp/src/gql/offer.gql.js
  webapp/src/routes/OfferPage/OfferPage.js
  webapp/src/routes/OfferPage/index.js
  webapp/src/routes/Offers/Offers.js
  webapp/src/routes/Offers/index.js
  webapp/src/routes/index.js
Labels: backend, frontend

#243 fix: improve offer management usability
  webapp/src/gql/offer.gql.js
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OffersManagement.js
Labels: bug, frontend
