Repository eoscostarica/lifebank, pull requests merged in 2020-11, with the labels that each got.

#335 feat: add logo to avatar
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/Home/ShowOffers.js
  webapp/src/routes/Home/ShowSponsors.js
Labels: frontend

#337 Feat/local business schema
  hapi/src/api/account.api.js
  hapi/src/routes/get-valid-sponsors/get-valid-sponsors.handler.js
  hapi/src/routes/get-valid-sponsors/get-valid-sponsors.route.js
  hapi/src/routes/index.js
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/LocalBusinessStructuredData/LocalBusinessStructuredData.js
  webapp/src/components/LocalBusinessStructuredData/index.js
  webapp/src/gql/account.gql.js
  webapp/src/routes/EditProfile/EditProfileSponsor.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
  webapp/src/utils/getOpeningHours.js
  webapp/src/utils/index.js
  webapp/yarn.lock
Labels: SEO

#348 feat: login/signup redesign
  webapp/src/components/LoginModal/Login.js
  webapp/src/components/LoginModal/LoginWithFacebook.js
  webapp/src/components/LoginModal/LoginWithGoogle.js
  webapp/src/components/Signup/Signup.js
  webapp/src/components/Signup/SignupAccount.js
  webapp/src/components/Signup/SignupConsent.js
  webapp/src/components/Signup/SignupDonor.js
  webapp/src/components/Signup/SignupLifeBank.js
  webapp/src/components/Signup/SignupRoleSelector.js
  webapp/src/components/Signup/SignupSponsor/SimpleRegisterForm.js
  webapp/src/components/Signup/SignupSponsor/index.js
  webapp/src/components/Signup/SignupUsername.js
  webapp/src/components/Signup/ValidateEmail.js
  webapp/src/components/Signup/index.js
  webapp/src/components/Signup/socialSingup/SignupWithFacebook.js
  webapp/src/components/Signup/socialSingup/SignupWithGoogle.js
  webapp/src/containers/SideBar.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/Home/HomeDesktop.js
  webapp/src/routes/Signup/Signup.js
  webapp/src/routes/index.js
Labels: frontend

#336 chore: update lifebank script
  contracts/scripts/lifebank.sh
Labels: smart contracts

#360 Conset section
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  webapp/src/components/ConsetComponent/ConsentComponent.js
  webapp/src/components/ConsetComponent/index.js
  webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
  webapp/src/components/LoginModal/Login.js
  webapp/src/components/Signup/Signup.js
  webapp/src/components/Signup/SignupAccount.js
  webapp/src/components/Signup/SignupConsent.js
  webapp/src/containers/SideBar.js
  webapp/src/containers/TopBar.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/Home/Home.js
  webapp/src/routes/Home/HomeDesktop.js
Labels: backend, frontend

#362 Seed data
  hapi/src/utils/lifebankcode.js
  seed/Insomnia_2020-11-10.json
  webapp/src/routes/Profile/ProfilePageSponsor.js
Labels: enhancement

#373 chore: update lifebank script
  contracts/scripts/lifebank.sh
Labels: smart contracts

#375 Fix/offer management bugs
  hapi/src/api/account.api.js
  hasura/migrations/1605801292935_alter_table_public_offer_alter_column_start_date/down.sql
  hasura/migrations/1605801292935_alter_table_public_offer_alter_column_start_date/up.sql
  hasura/migrations/1605801313178_alter_table_public_offer_alter_column_end_date/down.sql
  hasura/migrations/1605801313178_alter_table_public_offer_alter_column_end_date/up.sql
  hasura/migrations/1605801338054_alter_table_public_offer_alter_column_start_date/down.sql
  hasura/migrations/1605801338054_alter_table_public_offer_alter_column_start_date/up.sql
  hasura/migrations/1605801347620_alter_table_public_offer_alter_column_end_date/down.sql
  hasura/migrations/1605801347620_alter_table_public_offer_alter_column_end_date/up.sql
  webapp/package.json
  webapp/src/components/Logo/Logo.js
  webapp/src/components/LogoUrlInput/LogoUrlInput.js
  webapp/src/components/LogoUrlInput/index.js
  webapp/src/components/Schedule/Schedule.js
  webapp/src/components/Telephones/Telephones.js
  webapp/src/gql/offer.gql.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/EditProfile/EditProfile.js
  webapp/src/routes/EditProfile/EditProfileSponsor.js
  webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
  webapp/src/routes/OffersManagement/OfferDetails.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
  webapp/src/routes/Profile/ProfilePageSponsor.js
  webapp/yarn.lock
Labels: bug

#390 Fix/sponsor bugs
  hapi/src/api/account.api.js
  hapi/src/api/sponsor.api.js
  hasura/migrations/1605907933540_alter_table_public_user_alter_column_email/down.sql
  hasura/migrations/1605907933540_alter_table_public_user_alter_column_email/up.sql
  webapp/src/routes/EditProfile/EditProfileSponsor.js
Labels: bug

#394 Fix/insert email in location table
  hapi/src/api/sponsor.api.js
  webapp/src/components/Carousel/Carousel.js
  webapp/src/components/Logo/Logo.js
  webapp/src/components/OfferView/OfferView.js
  webapp/src/routes/EditProfile/EditProfileSponsor.js
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/InfoPage/InfoPage.js
  webapp/src/routes/Profile/ProfilePageLifebank.js
Labels: bug

#396 fix: enable font loading in the pipeline & other minor improvements
  nginx.conf
  webapp/nginx.conf
  webapp/package.json
  webapp/public/index.html
  webapp/src/components/Nearby/Nerby.js
  webapp/src/components/OfferView/OfferView.js
  webapp/src/index.js
  webapp/src/routes/Home/ShowLifebanks.js
  webapp/src/routes/Home/ShowOffers.js
  webapp/src/routes/Home/ShowSponsors.js
  webapp/src/routes/InfoPage/InfoPage.js
  webapp/yarn.lock
Labels: testing
